title: Renata Topinkova
logo: img/renata.png
email: renata.topinkova [at] lmu.de
description: >- # this means to ignore newlines until "baseurl:"
  Postdoc in Computational Social Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://renatatopinkova.github.io" # the base hostname & protocol for your site, e.g. http://example.com
favicon: true
color-scheme: auto

# build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji

remote_theme: BDHU/minimalist

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Publications
    icon: <i class="fa-solid fa-book-open"></i>
    link: publications
  - name: CV
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M4 0h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm5.5 1.5v2a1 1 0 0 0 1 1h2l-3-3z"/></g></svg>
    link: docs/topinkova_CV_tex.pdf
  - name: ResearchGate
    icon: <i class="fa-brands fa-researchgate"></i>
    link: https://www.researchgate.net/profile/Renata-Topinkova
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/renatatopinkova

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
